export const lightTheme = {
  BACKGROUND_COLOR: "#F7F1E9",
  DARKER_BACKGROUND_COLOR: "#CACBAB",

  MARKER_BACKGROUND_COLOR: "#4B4B4D",
  SELECTED_MARKER_BACKGROUND_COLOR: "#B26422",
  MARKER_TEXT_COLOR: "#F7F1E9",

  DEFAULT_BORDER_COLOR: "#9D9E9F",

  SPECIAL_TEXT_COLOR: "#B26422",

  TAG_BACKGROUND_COLOR: "#CACBAB",
  TAG_TEXT_COLOR: "#7A7B70",

  BUTTON_BACKGROUND_COLOR: "#4D6447",
};
